version: "3"
services:
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #     - ./certs:/var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email ant.goncharik.development@gmail.com --agree-tos --no-eff-email --force-renewal -d crypto-knight.online

  app:
    container_name: app
    image: antgoncharik/crypto-knight-dashboard
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
      - ./certs:/var/www/certbot
    # depends_on:
    #   certbot:
    #     condition: service_completed_successfully
