name: main

on:
  push:
    branches:
      - main

env:
  REGISTRY: antgoncharik
  IMAGE_NAME: crypto-knight-dashboard
  CONTAINER_NAME: crypto-knight-dashboard
  DOCKERHUB_USERNAME: antgoncharik

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build container image and push
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
          docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop ${{ env.CONTAINER_NAME }} || true
            docker rm ${{ env.CONTAINER_NAME }} || true
            docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker run -d -p 80:80 --restart=always --name ${{ env.CONTAINER_NAME }} -v /etc/letsencrypt:/etc/letsencrypt -v /var/lib/letsencrypt:/var/lib/letsencrypt ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
